export type SurfaceCondition =
  | 'dry_track_slick'     // mu ~ 1.45 (Warm slicks on high-grip asphalt)
  | 'dry_track_supersport'// mu ~ 1.25 (DOT race / Supercorsa SC)
  | 'dry_street_sport'    // mu ~ 1.05 (Standard premium sport tires on clean street)
  | 'wet_track'           // mu ~ 0.80 (Dedicated wet racing tires)
  | 'wet_street'          // mu ~ 0.55 (Damp/wet cold public asphalt)
  | 'greasy_cold';        // mu ~ 0.40 (Polished/cold/dirty asphalt)

export interface TireProfile {
  raw: string;            // e.g. "190_55_17" or "120/70-17"
  widthMm: number;        // e.g. 190
  aspectRatio: number;    // e.g. 55
  rimDiameterIn: number;  // e.g. 17
  outerRadiusM: number;   // overall rolling radius from axle to ground (m)
  crownRadiusM: number;   // cross-section crown curvature radius rt (m)
}

export interface CompoundGrip {
  condition: SurfaceCondition;
  label: string;
  muPeak: number;         // Peak friction coefficient (lateral/longitudinal)
  camberStiffnessCoeff: number; // Camber thrust multiplier k_gamma (relative to Fz)
}

export interface MotorcycleConfig {
  id: string;
  name: string;
  wheelbaseMm: number;
  massKg: number;
  cogHeightMm: number;
  maxMechLeanDeg: number;
  rearTireSize: string;
  frontTireSize: string;
}

export interface RiderConfig {
  massKg: number;
  hangOffCm: number;      // Lateral offset of rider torso/pelvis (0 to 35 cm)
  seatedHeightOffsetM?: number; // Distance of seated rider CoG above bike CoG (default ~0.28m)
}

export interface CornerScenario {
  speedMs: number;        // Forward velocity in m/s
  radiusM: number;        // Corner radius in meters
  longitudinalAccelG?: number; // Optional braking/throttle accel (+ for accel, - for braking)
}

export interface PhysicsResult {
  // Kinematics & Geometry
  speedMs: number;
  speedKmh: number;
  radiusM: number;
  turnRateDegS: number;   // Yaw angular velocity (deg/s)
  lateralAccelMs2: number;// v^2 / R
  lateralAccelG: number;  // ay / g

  // Lean Angles
  pointMassLeanDeg: number;   // Naive theta = atan(v^2 / gR)
  toroidalBikeLeanDeg: number;// True motorcycle lean angle (Cossalter equation)
  systemLeanDeg: number;      // Combined bike + rider CoG lean angle from vertical
  leanAngleDeltaDeg: number;  // Difference (toroidalBikeLean - pointMassLean)
  hangOffSavingsDeg: number;  // Degrees saved on bike lean due to rider hanging off

  // Tire & Contact Patch
  contactPatchOffsetMm: number; // Lateral migration of contact patch (rt * sin(theta))
  crownRadiusMm: number;

  // Dynamics & Grip (Pacejka + Camber Thrust)
  normalForceN: number;         // Combined vertical/normal tire force Fz
  requiredLateralForceN: number;// M * ay
  camberThrustN: number;        // Force generated by tire camber rolling cone
  slipAngleRequiredForceN: number; // Force left to be generated by slip angle
  peakLateralForceN: number;    // mu_peak * Fz
  gripUtilizationPct: number;   // (requiredLateralForce / peakLateralForce) * 100
  availableLongitudinalG: number; // Remaining grip on Kamm ellipse for braking/accel

  // Safety & Limits Flags
  isScrapingHardParts: boolean; // toroidalBikeLean >= maxMechLeanDeg
  isTractionLoss: boolean;      // gripUtilizationPct >= 100% (Low-side)
  isCombinedGripExceeded: boolean; // outside Kamm ellipse
  safetyStatus: 'optimal' | 'warning' | 'scraping' | 'lowside' | 'highside';
  statusMessage: string;
}
